FROM tensorflow/tensorflow:2.9.3-jupyter

RUN apt-get update && apt-get install -y libmagickwand-dev git && apt-get clean
RUN pip install --no-cache-dir -U pip

WORKDIR /workspace
RUN pip install --no-cache-dir \
    opencv-python-headless==4.6.*\
    rawpy==0.17.* \
    pandas \
    Pillow==7.1.2 \
    scikit-image==0.16.2 \
    scipy==1.4.1 \
    tqdm \
    Wand

CMD ["bash"]